name: Twice Daily Workflow

on:
  schedule:
    # Run at 00:00 UTC and 12:00 UTC every day
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with the specific version you need

      - name: Install dependencies and NLTK data
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -c "import nltk; nltk.download(['punkt', 'stopwords', 'wordnet', 'omw-1.4'])"
          mkdir -p /home/runner/nltk_data
          export NLTK_DATA=/home/runner/nltk_data
          python -c "import nltk; nltk.download(['punkt', 'stopwords', 'wordnet', 'omw-1.4'], download_dir='/home/runner/nltk_data')"
          echo "NLTK_DATA=/home/runner/nltk_data" >> $GITHUB_ENV

      

      # Step 4: Run your script with secrets
      - name: Run script using secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Running the script at $(date)"
          python pull_news_data.py

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Data/Raw_Data/*.csv
          git add Data/Processed_Data/*.csv
          git add Data/Processed_Data/Sentiment_Values/*.csv
          git add Data/Processed_Data/Graphic_Output/*.png
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-commit: Update data files and graphics" && git push)