name: Twice Daily Workflow

on:
  schedule:
    # Run at 00:00 UTC and 12:00 UTC every day
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with the specific version you need

            # Step 2: Cache pip dependencies (this goes BEFORE installing dependencies)
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 3: Install Python dependencies, including nltk
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all dependencies from requirements.txt
          pip install nltk  # Ensure nltk is explicitly installed

      # Step 4: Download NLTK data
      - name: Download NLTK Data
        run: |
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"



      # Step 4: Run your script with secrets
      - name: Run script using secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Running the script at $(date)"
          python pull_news_data.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Data/  # Staging the data folder
          git diff --quiet || git commit -m "Update data from Reddit API"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
